version: '3.1'
services:

  database:
    image: postgres:14-alpine
    container_name: postgres14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: foobar-db

  goserver:
    build:
      context: .
      dockerfile: DockerFiles/GoDockerFile
    restart: unless-stopped
    container_name: goserver-foobar
    ports:
       - "9000:9000"
    depends_on:
      database:
        condition: 
          service_started
       
  vueserver:
    build:
      context: .
      dockerfile: DockerFiles/VueDockerFile
    restart: unless-stopped
    container_name: vueserver-foobar
    depends_on:
      goserver:
        condition: 
          service_started
    ports:
       - "8080:8080"


networks:
  default:
    external:
      name: mock-network

volumes:
  data: