version: '3.1'
services:
  goserver:
    build:
      context: .
      dockerfile: DockerFiles/GoDockerFile
    restart: unless-stopped
    container_name: goserver-foobar
    ports:
       - "9000:9000"
       
  vueserver:
    build:
      context: .
      dockerfile: DockerFiles/VueDockerFile
    restart: unless-stopped
    container_name: vueserver-foobar
    
    ports:
       - "8080:8080"


networks:
  default:
    external:
      name: mock-network

volumes:
  data: