// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Events struct {
	ID         int64     `json:"id"`
	LocationID int64     `json:"location_id"`
	Name       string    `json:"name"`
	Datetime   int64     `json:"datetime"`
	CreatedAt  time.Time `json:"created_at"`
}

type Locations struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}
